const TOPICS = [
    "politics",
    "negativity",
    "controversy",
    "ads",
    "spam",
    "violence",
    "celebrity",
    "crypto",
    "clickbait",
    "memes",
    "NSFW",
    "finance",
    "sports",
];